prefix ex: <https://example.com/ns#>
prefix rdf: 	 <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

# CONSTRUCT {
# ?x ex:names ?names .
# ?names       rdf:first ?minName .
# ?currentItem rdf:rest  ?currentItem .
# ?currentItem rdf:first ?currentName .
# ?currentItem rdf:rest  ?nextItem .
# ?lastItem    rdf:first ?maxName . 
# ?lastItem    rdf:rest rdf:nil .
# }
Select * 
where {
   ?x ex:even ?even .
  {
    SELECT ?even (MIN(?name) AS ?minName) (MAX(?name) AS ?maxName)
    WHERE {
      ?y ex:name ?name .
      ?y ex:even ?even .
    } group by ?even
  }

  {
     SELECT ?currentName ?even (Min(?otherName) as ?nextName)
     WHERE {
            ?x ex:name ?currentName .
            ?x ex:even ?even .

            ?y ex:name ?otherName .
            ?y ex:even ?even2 .

            Filter (STR(?otherName) > STR(?currentName) && ?even = ?even2 )
     } group by ?currentName ?even
    }

    BIND(IRI(CONCAT(STR(?x), '-li-', STR(?minName))) AS ?names)
    BIND(IRI(CONCAT(STR(?x), '-li-', STR(?currentName))) AS ?currentItem)
    BIND(IRI(CONCAT(STR(?x), '-li-', STR(?nextName))) AS ?nextItem)
	BIND(IRI(CONCAT(STR(?x), '-li-', STR(?maxName))) AS ?lastItem)
} 
